### ISSUE TITLE
Package Question

### ISSUE THREAD

**Issue by asonnenschein** [ngds/data-archiver#15]
@jessica-azgs [Why give each CSW record linkage it's own directory?](https://github.com/ngds/data-archiver/blob/master/index.js#L56)

**Comment by smrgeoinfo** [comment]
I was thinking that the most likely mode of failure is for some file server to disappear; if we have the archive arranged according to the file servers that are actually hosting the resources, it will be easier to restore the contents of a server that has ungracefully gone offline.
